
package com.bird.settings;

import android.os.SystemProperties;
import android.text.TextUtils;

/** This Class is generated by Bird */

public final class BirdFeatureOption {
	public static final boolean BIRD_TWO_PAGE_SETTINGS = SystemProperties.getBoolean("ro.bdui.two_page_settings",false);//add by liuqipeng 20161018
    public static final boolean BIRD_TWO_TAB_SETTINGS = SystemProperties.getBoolean("ro.bdui.two_tab_settings",false);//add by liuzhiling @2016.7.7
    public static final boolean BIRD_PROXIMITY_CALIBRATION = SystemProperties.getBoolean("ro.bdfun.psensor_calibrate", false);
    public static final boolean BIRD_GSENSOR_CALIBRATION = SystemProperties.getBoolean("ro.bdfun.gsensor_calibrate", false);

    public static final boolean BIRD_MULTI_TOUCH = SystemProperties.getBoolean("ro.bdfun.multi_touch", false);
    public static final boolean BIRD_2POINT_TOUCH_VK = SystemProperties.getBoolean("ro.bdfun.2p_touch_vk", false);
    public static final boolean BIRD_3POINT_TOUCH_SCREENSHOT = SystemProperties.getBoolean("ro.bdfun.3p_touch_screenshot", false);
	public static final boolean BIRD_SETTING_MORE_RINGTONES = SystemProperties.getBoolean("ro.bdmisc.setting_more_ringtone", false);
	

    public static final boolean BIRD_DOOV_WALLPAPER_NOBG = SystemProperties.getBoolean("ro.bdfun.doov_wallpaper_nobg", false); //add by lichengfeng for fix bug #9427
    public static final boolean BIRD_RENAME_ALI_EXPERIENCE = SystemProperties.getBoolean("ro.bdfun.rename_ali_experience", false);//add by qinzhifeng 20151225

    public static final boolean BIRD_ADD_HOTKNOT = SystemProperties.getBoolean("ro.bdfun.add_hotknot", true);//add by qinzhifeng 20151231
    public static final boolean BIRD_RM_FACE_UNLOCK = SystemProperties.getBoolean("ro.bdfun.rm_face_unlock", false);//add by qinzhifeng 20160115
    public static final boolean BIRD_RM_POWER_SWITCH_MUSIC = SystemProperties.getBoolean("ro.bdfun.rm_power_switch_music", false);//add by qinzhifeng 20160115
    public static final boolean BIRD_FREE2USED = SystemProperties.getBoolean("ro.bdfun.free2used", false);//add by shenzhiwang,20160125
	public static final boolean BIRD_BATTERY_PERCENTAGE = SystemProperties.getBoolean("ro.bdfun.bird_battery_percent", false);//add by liuzhiling 20160706
    public static final boolean BIRD_FILES_PRESET = (SystemProperties.get("ro.bdfun.files_preset_loc").length() > 0);
    public static final boolean BIRD_LOCKSCREEN_SUNSHINE_MODE_SHOW = SystemProperties.getBoolean("ro.bdfun.ls_sunshine_show", false);//add by caizhaohui lockscreen sunshine mode open 20160217
    public static final boolean BIRD_MMITEST_DOOV_TEST_SENSOR =SystemProperties.getBoolean("ro.bdfun.doov_test_sensor",false);//add by fangbin 20160227 for doov mmitest
    public static final boolean BIRD_SHARE_SDCARD_SHOW_INTERNAL_STORAGE = SystemProperties.getBoolean("ro.bdfun.show_interal_storused", false);//add by caizhaohui for shared sdcard show internal storage 20160301
    public static final boolean BIRD_SYSTEM_SPACE = SystemProperties.getBoolean("ro.bdmisc.bird_system_space", false);
    public static final boolean BIRD_SETTING_DEVICE_INFO = SystemProperties.getBoolean("ro.bdfun.setting_device_info", false);//add by fangbin for device info 20160425
    public static final boolean BIRD_DOOV_BREATHLED = SystemProperties.getBoolean("ro.bdfun.doov_breathled", false);// task 7688 add by qinzhifeng 20160425
    public static final boolean BIRD_DOOV_ABOUT_PHONE_REMOVE_INFO = SystemProperties.getBoolean("ro.bdfun.doov_setting_rm_info", false);//add by fangbin for remove device info 20160505
    public static final boolean BIRD_SHOW_OUTDOORICON_IN_STAURSBAR = SystemProperties.getBoolean("ro.bdfun.show_outdoor_icon", false);//add by tianjianwei 2015/04/26
	public static final boolean BIRD_GALLER_FACE_DETECTION = SystemProperties.getBoolean("ro.bdfun_face_dete_gallery", false); //add by liuzhiling  20160712 
    public static final boolean BIRD_SHOW_SHULIAN_FOTA = SystemProperties.getBoolean("ro.bdfun.shulian_fota", false);//add by lvhuaiyi for shulian fota
    public static final boolean BIRD_A200_CUSTOM = SystemProperties.getBoolean("ro.bdfun.a200_custom", false); //custom A200 add by lichengfeng  @20160406
    public static final boolean BIRD_POWER_SAVING = SystemProperties.getBoolean("ro.bdfun.power_saving", false);//add by ludaxu 20160618 for power saving
    public static final boolean BIRD_IMEI_BY_ABD = SystemProperties.getBoolean("ro.bdfun.imei_by_adb", false);//bird, imei by adb, add by shenzhiwang @20160705
	public static final boolean BIRD_REMOVE_TURBO_DOWNLOAD = SystemProperties.getBoolean("ro.bdfun.remove_turbo_download", false);//added by WangBiyao 20160707
	public static final boolean BIRD_ENABLE_ENCRYPTION = SystemProperties.getBoolean("ro.bdfun.encryption", false);
	public static final boolean BIRD_HIDE_SCREEN_PINNING = SystemProperties.getBoolean("ro.bdfun.hide_scr_pinning",false );//add by ningzhiyu 20160711, default false
	public static final boolean BIRD_REMOVE_USB_MIDI_MENU = SystemProperties.getBoolean("ro.bdmisc.rm_usb_midi_menu", true);
	public static final boolean BIRD_SIMTOOLKIT_INSETINGS = SystemProperties.getBoolean("ro.bdfun.simtoolinsettings", true);//add by meifangting 20150417
	public static final boolean BIRD_DEVICE_INFO_CPU_MODEL = SystemProperties.getBoolean("ro.bdfun.cpu_model", false);
		public static final boolean BIRD_DEVICE_INFO_CPU_CORE = SystemProperties.getBoolean("ro.bdfun.cpu_core", false);
    public static final boolean BIRD_DEVICE_INFO_CPU_FREQUENCY = SystemProperties.getBoolean("ro.bdfun.cpu_frequency", false);
    public static final boolean BIRD_DEVICE_INFO_PHONE_MEMORY = SystemProperties.getBoolean("ro.bdfun.phone_memory", false);
    public static final boolean BIRD_DEVICE_INFO_SYSTEM_MEMORY = SystemProperties.getBoolean("ro.bdfun.system_memory", false);
	public static final boolean BIRD_REMOVE_MTK_CUSTOM_BUILD_VERSION_MENU = SystemProperties.getBoolean("ro.bdmisc.rm_cust_build_menu", true);
	// @ { BIRD zhouleigang 20141020, BIRD_AUDIO_CLAM_RING begin
    public static final boolean BIRD_AUDIO_CLAM_RING = SystemProperties.getBoolean("ro.bdfun.clam_ring", false);
    // @ }
	public static final boolean BIRD_OPEN_MOBILE_DATA_WORK_LEAGOO = SystemProperties.getBoolean("ro.bdfun.bird_open_mobile_data", false);//added by WangBiyao 20160706
	public static final boolean BIRD_SCTIME_OUT_NEVER= SystemProperties.getBoolean("ro.bdmisc.sctimeout_never", false);//added by WangBiyao 20160711
	/// bird: BUG #14307, for sd card , remove "Format as internal" menu, chengting, @20160802 {
	public static final boolean BIRD_SD_CARD_FORMAT_AS_INTERNAL_MENU = SystemProperties.getBoolean("ro.bdfun.sd_as_internal_menu",false);
	/// @}

	public static final boolean BIRD_GEMINI_DEFAULT_DATA_ON = SystemProperties.getBoolean("ro.bdfun.auto_cellular_data", false);
	public static final boolean BIRD_GEMINI_DEFAULT_DATA_ON_ALWAYS = SystemProperties.getBoolean("ro.bdfun.always_cellular_data", false);
	/// bird: BUG #15174, remove accessibility -- global gesture menu, chengting, @20160810 {
	public static final boolean BIRD_GLOBAL_GESTURE_MENU = SystemProperties.getBoolean("ro.bdfun.global_ges_menu",true);
	/// @}
	/// bird: BUG #15235, BIRD_USB_MODE_DATA_UNLOCK, chengting,@20160811 {
	public static final boolean BIRD_USB_MODE_DATA_UNLOCK = SystemProperties.getBoolean("ro.bdfun.usb_data_unlock",false);
	/// @}
	
	/*bird add by liuzhenting 20160815 begin*/
	 public static final boolean BIRD_NEW_STORAGE = SystemProperties.getBoolean("ro.bdfun.new_storage", false);
	 /*bird add by liuzhenting 20160815 end*/
	 
    // @ { BIRD jiali 20160815, BIRD_FLIP_ANSWER_CALL_MENU begin
    public static final boolean BIRD_FLIP_ANSWER_CALL_MENU = SystemProperties.getBoolean("ro.bdfun.flip_answer_call_menu", false);
    // @ }
	public static final boolean BIRD_SMART_MOT_IN_SETTING = SystemProperties.getBoolean("ro.bdfun.smart_mot_in_Setting", true);///bird:BIRD_SMART_MOT_IN_SETTING,liuchaofei @20160816
	public static final boolean BIRD_3P_TOUCH_SCREENSHOT_INACCESSIBILITY = SystemProperties.getBoolean("ro.bdfun.3p_scr_shot_in_access", false); ///bird:BIRD_3P_TOUCH_SCREENSHOT_INACCESSIBILITY,liuchaofei @20160816
}
