
package com.bird.contacts;

import android.os.SystemProperties;
import android.text.TextUtils;

/** This Class is generated by Bird */

public final class BirdFeatureOption {
	//do not need open BIRD_DOOV_SOUND 
	//that means if BIRD_DOOV_DIAPAD_SOUND_SINGLE is true then BIRD_DOOV_SOUND should be false in diapad;
	public static final boolean BIRD_DOOV_SOUND = false;
	//SystemProperties.getBoolean("ro.bdfun.doov_sound", false);//[BIRD_DOOV_SOUND] add by lichengfeng 20160601
	
	public static final boolean BIRD_DOOV_DIAPAD_SOUND_SINGLE = SystemProperties.getBoolean("ro.bdfun.doov_dp_sound_single", false);//[BIRD_DOOV_DIAPAD_SOUND_SINGLE] add by lichengfeng 20160601	
	
	public static final boolean BIRD_TWO_IMEI_EQUALS_SHOW_ONE_OPEN = SystemProperties.getBoolean("ro.bdfun.two_imei_show_one", false);//add by lichengfeng two imei equals just show one @20160413
	public static final boolean BIRD_DIALPAD_SPEECH_NUMBNER = SystemProperties.getBoolean("ro.bdfun.elder_launcher", false);//elder launcher add by meifangting 20160516
	public static final boolean BIRD_OLDMAN_Q451 = SystemProperties.getBoolean("ro.bdfun.old_man_q451", false);
    public static final boolean BIRD_DOOV_INCALL_MARK_NUMBER = SystemProperties.getBoolean("ro.bdfun.doov_incall_mark_num", true);//doov stranger-call new mark-dialog add by liuqipeng 20160918
}
